CREATE DATABASE StaffManagement;
GO

USE StaffManagement;
GO

CREATE TABLE ACCOUNT (
    ACCOUNTID VARCHAR(255) NOT NULL PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE INT NOT NULL
);

CREATE TABLE DEPARTMENT (
    DEPARTMENTID VARCHAR(255) NOT NULL PRIMARY KEY,
    DEPARTMENTNAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255)
);

CREATE TABLE PROJECT (
    PROJECTID VARCHAR(255) NOT NULL PRIMARY KEY,
    PROJECTNAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255)
);

CREATE TABLE EMPLOYEE (
    EMPLOYEEID VARCHAR(255) PRIMARY KEY,
    EMPLOYEENAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PHONE VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    DEPARTMENTID VARCHAR(255),
    FOREIGN KEY (DEPARTMENTID) REFERENCES DEPARTMENT (DEPARTMENTID)
);

CREATE TABLE EMPLOYEE_PROJECT (
    EMPLOYEEID VARCHAR(255),
    PROJECTID VARCHAR(255),
    FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEE (EMPLOYEEID),
    FOREIGN KEY (PROJECTID) REFERENCES PROJECT (PROJECTID)
);