CREATE DATABASE EmployeManagement;
GO

USE EmployeManagement;
GO

CREATE TABLE ACCOUNT (
    ACCOUNTID INT NOT NULL PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
     ROLE VARCHAR(20) NOT NULL
);

CREATE TABLE DEPARTMENT (
    DEPARTMENTID INT NOT NULL PRIMARY KEY,
    DEPARTMENTNAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255)
);

CREATE TABLE PROJECT (
    PROJECTID INT NOT NULL PRIMARY KEY,
    PROJECTNAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255)
);

CREATE TABLE EMPLOYEE (
    EMPLOYEEID INT PRIMARY KEY,
    EMPLOYEENAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PHONE VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    DEPARTMENTID INT,
    FOREIGN KEY (DEPARTMENTID) REFERENCES DEPARTMENT (DEPARTMENTID)
);

CREATE TABLE EMPLOYEE_PROJECT (
    EMPLOYEEID INT,
    PROJECTID INT,
    FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEE (EMPLOYEEID),
    FOREIGN KEY (PROJECTID) REFERENCES PROJECT (PROJECTID),
    PRIMARY KEY (EMPLOYEEID, PROJECTID)
);

CREATE TABLE EMPLOYEE_ACCOUNT (
    EMPLOYEEID INT,
    ACCOUNTID INT,
    FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEE (EMPLOYEEID),
    FOREIGN KEY (ACCOUNTID) REFERENCES ACCOUNT (ACCOUNTID),
    PRIMARY KEY (EMPLOYEEID, ACCOUNTID)
);
